name: RAFT (Reusable Automation for Testing)

on:
  push:
    branches:
    - master
    - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.11 ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          flake8 .

  test:
    runs-on: ubuntu-latest
    needs:
      - lint
    strategy:
      matrix:
        python-version: [ 3.11 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run integration tests
        run: |
          py.test -s -m reqres

      - name: Save allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: ./allure-results

  report:
    runs-on: ubuntu-latest
    needs:
      - test
    strategy:
      matrix:
        python-version: [ 3.11 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download allure results
        uses: actions/download-artifact@v3
        with:
          name: allure-results
          path: ./allure-results

      - name: Set up allure command-line tool
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.14.0/allure-2.14.0.zip
          unzip allure-2.14.0.zip

      - name: Generate HTML report from allure results
        run: |
          ./allure-2.14.0/bin/allure generate allure-results --clean -o allure-report

      - name: Save allure report artifacts
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: ./allure-report