name: RAFT (Reusable Automation for Testing)

on:
  push:
    branches:
    - master
    - develop

  pull_request:
    branches:
    - master
    - develop

jobs:

  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        with:
          args: "--max-line-length=100 --ignore E501,E266,W503,E203,E722"
        run: |
          flake8 .

  test:
    runs-on: ubuntu-latest

    needs:
      - lint

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run integration tests
        run: |
          py.cleanup -p && py.test -m reqres
